### ISSUE TITLE
Spotify++ ETA

### ISSUE THREAD

**Issue by dongmin-dev** [vizunchik/AltStoreRus#1]
the new Spotify++ 8.5.53 you updated has 44 hours of ETA

**Comment by dongmin-dev** [comment]
Spotify 8.5.53 download url is outdated

**Comment by vizunchik** [comment]
It will be available when the time expires

**Comment by dongmin-dev** [comment]
> It will be available when the time expires

Where can I contact you?

**Comment by vizunchik** [comment]
what do you want? To be honest, I went to sleep and will answer later)

**Comment by dongmin-dev** [comment]
What does "Size" line do?

**Comment by vizunchik** [comment]
size of the ipa file

**Comment by dongmin-dev** [comment]
ok thx dude you are god 👍👍 answer me the last question, Did you make the tweaked Spotify 8.5.53 ?

**Comment by vizunchik** [comment]
in the description like all wrote
8.5.53 works, but there spotilife 1.0a (not 1.1a)
